# Generated by Django 5.0 on 2023-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=2083)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('content', models.TextField()),
                ('color', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('Additional_Information', models.TextField()),
                ('Shipping_Returns', models.TextField()),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('reviews', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
