# Generated by Django 5.0 on 2023-12-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('silver', 'Silver'), ('gold', 'Gold'), ('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple')], max_length=255),
        ),
    ]
