# Generated by Django 5.0 on 2023-12-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_category_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
